# Generated by Django 5.2.3 on 2025-06-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('language_code', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский')], default='uz', max_length=2)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Nomi (RU)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Nomi (RU)')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Asosiy rasm')),
                ('categories', models.ManyToManyField(related_name='products', to='shop.category', verbose_name='Kategoriyalar')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name_uz', models.CharField(max_length=100, verbose_name='Rang nomi (UZ)')),
                ('color_name_ru', models.CharField(max_length=100, verbose_name='Rang nomi (RU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'verbose_name': 'Mahsulot varianti (rang)',
                'verbose_name_plural': 'Mahsulot variantlari (ranglar)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variants/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant')),
            ],
        ),
    ]
